### ISSUE TITLE
updater for `mepid.json`

### ISSUE THREAD

**Issue by yetzt** [TechToThePeople/mep#11]
downloader for `mepid.json` is commented out since the resource is gone. implement a replacement.

**Comment by tttp** [comment]
IMO no need, it was mostly to do some QA... and since I didn't notice it
was  gone, probably not that good at it

**Comment by yetzt** [comment]
it's used in aliases and transform, i'll investigate (later).

**Comment by yetzt** [comment]
nevermind, it's updated in `meps_str.js`.
