### ISSUE TITLE
Project has no License

### ISSUE THREAD

**Issue by marado** [TechToThePeople/mep#3]
I'd like to see it with a free software license, but even if you're not inclined to do that, it would be nice to have some license.

**Comment by tttp** [comment]
Hi, very good point. My go to licenses are MIT or agpl3. I think the later would fit better here. Thought?

However, the bigger problem I have is that for this project or for MEPwatch, it's mostly data, so a software licence might not work very well here. Any suggestion?

**Comment by marado** [comment]
AGPLv3 for software and ODbL for data would be my suggestion.

**Comment by tttp** [comment]
I know it's been a long time, but if you PR me these  (+convenant's code?) I'd gladly merge it

**Comment by marado** [comment]
ĩ just realized that a License is actually stated: ISC, in https://github.com/TechToThePeople/mep/blob/master/package.json#L52 . I suppose it is there by mistake?

**Comment by tttp** [comment]
Duh, I usually go for aGPL3 too. yeah, ISC was probably a default that sneaked in and a mistake indeed

**Comment by yetzt** [comment]
default license was changed to `UNLICENSED` in 3175c51e2c51c2180b030fc680f49b139e9ce3b2
@tttp please specify the desired license.

**Comment by yetzt** [comment]
according to the [LICENSE](https://github.com/TechToThePeople/mep/blob/production/LICENSE) file it's AGPL, so i changed it to `AGPL-3.0-or-later`
