### ISSUE TITLE
Fix gulp

### ISSUE THREAD

**Issue by tttp** [TechToThePeople/mep#7]
gulp breaks
it needs to call script/transform.js, but that breaks... unless your run it separately/by hand

by fix gulp, I mean: or find a more modern way to run a bunch of scripts and monitor if it breaks 

warning: 
- the number of MEPs can go under 705 (if one leaves before being replaced)
- the gender is added manually by me (useful for campaigning, Liebe vs Lieber...)
- they seem to create new delegations regularly, this part isn't used, doesn't matter much
- new committees matter
- the name of eugroups changes from time to time (eg alde->renew) and fuck up everything

**Comment by yetzt** [comment]
gulp breaking should be fixed in f023b617fea1c5f76117539c8e7645eca4f26413

**Comment by tttp** [comment]
awesome. can you PR it? (and merge directly)

**Comment by yetzt** [comment]
merged
