### ISSUE TITLE
get data from wikidata

### ISSUE THREAD

**Issue by tttp** [TechToThePeople/mep#8]
This one is a nice to have/if it's easy

get extra data from wikidata, especially 
- twitter accounts that aren't on europarl
- information about constituencies (either officially, like for the belgium MEPs or unofficial ones, like that german MEPs are informally divided, like CSU -> Bavaria)

**Comment by yetzt** [comment]
it is possible to query for all entries that have a [MEP directory ID](https://www.wikidata.org/wiki/Property:P1186), with the query [`SELECT DISTINCT ?item WHERE { ?item p:P1186 ?statement0. ?statement0 (ps:P1186) _:anyValueP1186. }
`](https://query.wikidata.org/sparql?query=SELECT%20DISTINCT%20%3Fitem%20WHERE%20%7B%0A%20%20%3Fitem%20p%3AP1186%20%3Fstatement0.%0A%20%20%3Fstatement0%20(ps%3AP1186)%20_%3AanyValueP1186.%0A%7D%0A&format=json)

**Comment by yetzt** [comment]
wikidata scraper added in 5c15cedfad35a9cfd2c4b026c9885f04b914d7f7
data added in ea0e555c4639465e204c8648b3459c0cec2df7ef
